// Regenerates src/abi.ts from Foundry build output. Run after `forge build`.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const out = path.join(root, "contracts/out");
const contracts = [
  "Entrypoint", "ZipPrivacyPool", "ZipBroadcaster", "ZipDoorstep", "ZipRezip", "ZipAddressRegistry",
  "ZipMerchants", "ZipPay", "ZipCouriers", "ZipBadges", "ZipSignal", "ZipPolls", "Semaphore", "BatchRelayer", "ZcRewardsHarvester", "ZipLiquidityBands",
];
let ts = "// Generated by scripts/gen-abi.mjs from contracts/out. Do not edit.\n\n";
for (const c of contracts) {
  const abi = JSON.parse(fs.readFileSync(path.join(out, `${c}.sol`, `${c}.json`), "utf8")).abi;
  const name = c === "ZipPrivacyPool" ? "poolAbi" : c[0].toLowerCase() + c.slice(1) + "Abi";
  ts += `export const ${name} = ${JSON.stringify(abi)} as const;\n\n`;
}
fs.writeFileSync(path.join(root, "packages/sdk/src/abi.ts"), ts);
console.log("wrote packages/sdk/src/abi.ts");
